# Generated by Django 3.0.7 on 2020-08-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_hotels_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
