# Generated by Django 3.0.7 on 2020-08-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotels'),
        ),
    ]
