# Generated by Django 3.0.7 on 2020-08-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_rooms_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
