# Generated by Django 3.0.7 on 2020-08-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_auto_20200805_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotels'),
        ),
    ]
